# fuel cell engine, DC/DC converter, and motor model
# and health model of FCE

import math
import numpy as np
from scipy.interpolate import interp1d, RegularGridInterpolator # interp1d: 1D linear interpolation function
import scipy.io as scio


class FCHEV_SOH:
    def __init__(self):
        self.simtime = 1.0        # length of a time step
        # fuel cell model
        self.motor_max_power = 120000  # W, 120kW
        self.P_FC_max = 95.0   # kW
        self.P_FC_high = 0.9 * self.P_FC_max        #FC degradation threshold 1
        self.P_FC_low = 0.05 * self.P_FC_max         #FC degradation threshold 2
        self.P_FC_off = 0.01 * self.P_FC_max
        self.P_FC_load_change_rate_thresh = 0.1 * self.P_FC_max   # kW/s
        self.P_FC_old = 0       # power of last time step and in this case, initial value is 0 kW
        self._func_init()       # load data from FCHEV data files (FCS, fuel consumption, FC efficiency)
    
    def _func_init(self):
        data_dir = "/home/chahyunjoon/dev/FCEV-EMS/project-data/FCHEV_data/"  
        # fuel cell
        data = scio.loadmat(data_dir+'P_fc_stack_nexo.mat')
        P_fc = data['P_fc_stack'][0]   # gross electrical power generated by the fuel cell stack itself: kW
        data = scio.loadmat(data_dir+'P_fc_sys_nexo.mat')
        P_fce = data['P_fc_sys'][0]   # net electrical power generated by the fuel cell system: kW
        data = scio.loadmat(data_dir+'fuel_flow_nexo.mat')
        h2_consumption = data['fuel_flow_vec'][0]
        data = scio.loadmat(data_dir+'Eff_fc_nexo.mat')
        fce_eff = data['Eff_fc'][0]
        # making linear mapping of P_fc to P_fce
        # extrapolate means that for input values outside the range of the data
        # the function will return values based on the linear trend of the data
        self.P_fce = interp1d(P_fc, P_fce, kind='linear', fill_value='extrapolate') # system power corresponding to stack power
        self.fce_eff = interp1d(P_fc, fce_eff, kind='linear', fill_value='extrapolate') # FC efficiency corresponding to stack power
        self.h2_consumption = interp1d(P_fc, h2_consumption, kind='linear', fill_value='extrapolate') # hydrogen consumption corresponding to stack power
        
        # motor scaled to 120kw Nexo motor data
        # motor efficiency map 
        data = scio.loadmat(data_dir+'mot_eff_nexo.mat')
        motor_eff = data['mot_eff_nexo']
        #motor speed and torque grid points
        data = scio.loadmat(data_dir+'W_mot_nexo.mat')
        motor_spd = data['W_mot_nexo'][0]
        data = scio.loadmat(data_dir+'T_mot_nexo.mat')
        motor_trq = data['T_mot_nexo'][0]
        # create 2D interpolation function for motor efficiency map: x축 trq, y축 spd에 따른 효율 cmap 생성
        self._mot_eff_interp = RegularGridInterpolator(
            (motor_trq, motor_spd), motor_eff,
            method='linear', bounds_error=False, fill_value=None
        )
        self.mot_eff_map = lambda w, t: float(self._mot_eff_interp((t, w)))

        # motor torque lower limits extrapolation
        data = scio.loadmat(data_dir+'mot_trq_min_nexo.mat')
        mot_trq_min = data['mot_trq_min_nexo']
        self.mot_trq_min = interp1d(mot_trq_min[:, 0], mot_trq_min[:, 1], kind='linear', fill_value='extrapolate')

        # motor torque upper limits extrapolation
        data = scio.loadmat(data_dir+'mot_trq_max_nexo.mat')
        mot_trq_max = data['mot_trq_max_nexo']
        self.mot_trq_max = interp1d(mot_trq_max[:, 0], mot_trq_max[:, 1], kind='linear', fill_value='extrapolate')
        
        # DC/DC (connects FC system to motor/battery)
        data = scio.loadmat(data_dir+'dcdc_eff_nexo.mat')
        DCDC_eff = np.ravel(data['eff_dcdc'])
        data = scio.loadmat(data_dir+'P_fc_sys_nexo.mat')
        P_DCDC = np.ravel(data['P_fc_sys'])      # kW
        self.DCDC_eff = interp1d(P_DCDC, DCDC_eff, kind='linear', fill_value='extrapolate')
        
    def _FCE_is_ON(self, P_FCE):
        return P_FCE >= self.P_FC_off

    def load_change_cycle_count(self, P_fc, P_fc_old):
        P_fc_arr = np.asarray(P_fc, dtype=np.float64)
        P_fc_old_arr = np.asarray(P_fc_old, dtype=np.float64)
        ramp_rate = np.abs(P_fc_arr - P_fc_old_arr) / max(self.simtime, 1e-12)
        return np.where(ramp_rate > self.P_FC_load_change_rate_thresh, 1.0, 0.0)
    
    @staticmethod
    # vehicle model: calculate torque, speed, and power at given car speed and acceleration(axle)
    def T_W_axle(car_spd, car_acc):
        # parameters of car
        wheel_radius = 0.355  # 19inch wheel의 외경=710mm ~ 715mm -> radius=0.355 m
        mass = 1900  # kg      # Nexo 1900kg
        C_roll = 0.012       # 0.0085         # [0.012， 0.015]
        density_air = 1.226  # N*s2/m4
        area_frontal = 2.5  # Overall height=1630mm, Overall width=1860mm, Area=2.4~2.6m2
        G = 9.81
        C_d = 0.32  
        G_f = 7.98  # Final gear ratio
        rads2rpm = 2*math.pi/60
        # calculate
        # W_axle = car_spd/wheel_radius*G_f  # r per second
        W_axle = car_spd/wheel_radius*G_f/rads2rpm      # rpm
        # torque: driving resistance = (R/gear ratio) * (force + rolling resistance + aerodynamic resistance) -> Nm
        T_axle = wheel_radius/G_f*(mass*car_acc+mass*G*C_roll+0.5*density_air*area_frontal*C_d*(car_spd**2))
        #0.98 and 0.95 are driveline efficiency for motoring and generating respectively
        if T_axle >= 0: # car is accelerating
            P_axle = rads2rpm*T_axle*W_axle/0.98   
        else:  # car is decelerating
            P_axle = rads2rpm*T_axle*W_axle*0.95   
        return T_axle, W_axle, P_axle # 이 값들이 이제 motor model로 들어감

    # motor model: calculate torque, speed, efficiency, and power at given axle torque, speed, and power
    # regen braking시 motor로 들어오는 power calculation included
    def run_motor(self, T_axle, W_axle, P_axle):
        T_mot = T_axle
        W_mot = W_axle
        # 주어진 속도에 따른 torque limit
        T_mot_max = self.mot_trq_max(W_mot)
        T_mot_min = self.mot_trq_min(W_mot)
        #minimum, maximum value clamping
        if T_mot < T_mot_min:
            T_mot = T_mot_min
        if T_mot > T_mot_max:
            T_mot = T_mot_max
        mot_eff = self.mot_eff_map(W_mot, T_mot)
        rads2rpm = 2*math.pi/60
        # 입력된 P_axle에 따라 motor power 산출
        if P_axle <= 0:
            # P_mot = P_axle*mot_eff: regen brake시 mechanical energy가 electrical energy로 변환되는 양. 
            P_mot = rads2rpm * T_mot * W_mot * mot_eff
        else:
            # P_mot = P_axle/mot_eff: 출력요구치만큼 traction하기 위해서 필요한 motor electirical power의 양.
            P_mot = rads2rpm*T_mot*W_mot/mot_eff
        return T_mot, W_mot, mot_eff, P_mot
    
    # FC and DC/DC converter model
    def run_fuel_cell(self, P_fc):
        P_fc_arr = np.asarray(P_fc, dtype=np.float64)
        scalar_input = P_fc_arr.ndim == 0
        if scalar_input:
            P_fc_arr = P_fc_arr.reshape(1)
        #여기까지 data type을 numpy array로 synchronize
        # Power levels:
        # P_fc (stack power) -> P_fce (net FC system power after stack/BOP losses)
        # -> P_dcdc (DC/DC output power delivered to the DC bus)
        fc_active = P_fc_arr >= self.P_FC_off
        P_fce = np.zeros_like(P_fc_arr, dtype=np.float64)
        fce_eff = np.full_like(P_fc_arr, np.nan, dtype=np.float64)
        h2_fcs = np.zeros_like(P_fc_arr, dtype=np.float64)
        dcdc_eff = np.full_like(P_fc_arr, np.nan, dtype=np.float64)
        P_dcdc = np.zeros_like(P_fc_arr, dtype=np.float64)

        if np.any(fc_active):
            P_fc_active = P_fc_arr[fc_active]
            P_fce_active = np.asarray(self.P_fce(P_fc_active), dtype=np.float64).reshape(-1)
            fce_eff_active = np.asarray(self.fce_eff(P_fc_active), dtype=np.float64).reshape(-1)
            h2_fcs_active = np.asarray(self.h2_consumption(P_fc_active), dtype=np.float64).reshape(-1) / 60.0
            dcdc_eff_active = np.asarray(self.DCDC_eff(P_fce_active), dtype=np.float64).reshape(-1)

            P_fce[fc_active] = P_fce_active
            fce_eff[fc_active] = fce_eff_active
            h2_fcs[fc_active] = h2_fcs_active
            dcdc_eff[fc_active] = dcdc_eff_active
            P_dcdc[fc_active] = dcdc_eff_active * P_fce_active
        # input이 scalar였을 경우, 출력시 scalar로 conversion 
        if scalar_input:
            #np.ravel(): n-D array을 1-D array로 평탄화
            P_fce_val = float(np.ravel(P_fce)[0])
            fce_eff_val = float(np.ravel(fce_eff)[0])
            h2_fcs_val = float(np.ravel(h2_fcs)[0])
            dcdc_eff_val = float(np.ravel(dcdc_eff)[0])
            P_dcdc_val = float(np.ravel(P_dcdc)[0])
            info = {'P_fc': float(P_fc_arr[0]), 'P_fce': P_fce_val, 'fce_eff': fce_eff_val,
                    'dcdc_eff': dcdc_eff_val, 'h2_fcs': h2_fcs_val, 'P_dcdc': P_dcdc_val}
            return P_dcdc_val, h2_fcs_val, info
        #np.ravel(): n-D array을 1-D array로 평탄화
        P_fc_arr = np.ravel(P_fc_arr)
        P_fce = np.ravel(P_fce)
        fce_eff = np.ravel(fce_eff)
        h2_fcs = np.ravel(h2_fcs)
        dcdc_eff = np.ravel(dcdc_eff)
        P_dcdc = np.ravel(P_dcdc)
        info = {'P_fc': P_fc_arr, 'P_fce': P_fce, 'fce_eff': fce_eff, 'dcdc_eff': dcdc_eff,
                'h2_fcs': h2_fcs, 'P_dcdc': P_dcdc}
        return P_dcdc, h2_fcs, info
    
    # fuel cell health model: calculate fuel cell degradation at given fuel cell power
    def run_FC_SOH(self, P_fc):
        # degradation percentage per second -> Reference: 2020 Song et al 
        # 2008 Pei et al. degradation model(100cell, effective area 280cm^2, FC bus) 사용한 연구 중 하나 
        prev_on = bool(self._FCE_is_ON(self.P_FC_old))
        curr_on = bool(self._FCE_is_ON(P_fc))
        # start-stop cycles (per hour)
        if (not prev_on) and curr_on:
            # d_s_s = self.simtime * 1.96 * 1e-3 / 3600 
            d_s_s = self.simtime*1.96
        else:
            d_s_s = 0
        # low-power load condition (per hour)
        if curr_on and P_fc < self.P_FC_low:
            # d_low = self.simtime * 1.26 * 1e-3 / 3600
            d_low = self.simtime*1.26
        else:
            d_low = 0
        # high-power load condition (per hour)
        if P_fc >= self.P_FC_high:
            # d_high = self.simtime * 1.47 * 1e-3 / 3600      # 1e-3/3600 == 2.8e-7
            d_high = self.simtime*1.47
        else:
            d_high = 0
        # load changing cycles (per cycle)
        # absolute value of load variations rate is larger than 10% of max power per second
        d_l_c = 5.93 * float(np.asarray(self.load_change_cycle_count(P_fc, self.P_FC_old), dtype=np.float64).reshape(()))

        # total degradation in current time step
        De_i = (d_s_s + d_low + d_high) * 1e-3 / 3600 + d_l_c*1e-5   # in percentage
        FCS_De = De_i / 100      # 10% is the allowed performance degradation percentages\
        out_info = {'d_s_s': d_s_s, 'd_low': d_low, 'd_high': d_high, 'd_l_c': d_l_c,
                    'FCS_De': FCS_De}
        self.P_FC_old = P_fc
        return FCS_De, out_info
    
